#!/usr/bin/env bash
set -e -o pipefail

basedir=$(cd "$(dirname "$0")" && pwd -P)

wget --version >/dev/null || {
    echo 1>&2 "$(basename "$0"):" "'wget' not installed?"
    exit 50    # wget uses error codes up to 10 or so
}

cd "$basedir"
wget --no-verbose --mirror "$@" https://lists.tlug.jp/
